### ISSUE TITLE
[PRM] CRUD for confident persons

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.api#14]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/partnership-relations-management/declarations/update-confident-person)

**Comment by gmile** [comment]
@lymychp we'll be adding `/api/persons` endpoint, so this issue becomes a more generic, e.g. CRUD for confident persons.

**Comment by gmile** [comment]
@lymychp in fact confident persons thing is [moving to MPI](https://github.com/Nebo15/ehealth.api/commit/76f1938fb6c9ee91b58d96f0cddb105d708f7278), so I guess the issue is no longer applicable to this repo?

**Comment by lymychp** [comment]
@gmile that's correct. I will reject this ticket.
