### ISSUE TITLE
[IL] Create Declaration service

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.api#27]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/medical-service-provider-integration-layer/declarations/create-declaration) and service [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Create+declaration)

**Comment by gmile** [comment]
There is no IL yet, this is being implemented on the UI.

The issues should be re-opened in a new repo for IL project.
