### ISSUE TITLE
[MPI/PRM] Some dates are returned in wrong format - return date as date

### ISSUE THREAD

**Issue by gmile** [Nebo15/prm.api#42]
Reproduce

1. Fetch doctors index endpoint:

  ```
  curl http://104.155.75.171/api/doctors/
  ```

2. See some dates for returned objects are specified in the following format:

  ```
  03-03-2001
  ```

This is not correct. Expected format should follow ISO 8601. Dates in correct format, for example, should look like this:

  ```
2012-04-23T18:25:43.511Z
  ```

**Comment by AndrewDryga** [comment]
Your suggested format is incorrect. In places where we return date, we don't need to specify time (and we don't have/store it).


Format `01-01-2010` is a bug, should be: `2010-01-01` (also a valid ISO representation).

**Comment by gmile** [comment]
@AndrewDryga you're right.

I meant:
```
2012-04-23
```
but typed (actually blame copy-pasta!):

```
2012-04-23T18:25:43.511Z
```
