### ISSUE TITLE
[PRM] "Search Doctor" service

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.api#5]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/partnership-relations-management/doctors/search-doctor)

**Comment by gmile** [comment]
FYI, maybe consider https://github.com/aditya7iyengar/rummage_phoenix here?

**Comment by gmile** [comment]
Resolved in #36 (disregard the PR title there)
