### ISSUE TITLE
[IL] Check phone number

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/prm.api#72]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/phone-verification/check-phone-number)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Check+phone+number)

**Comment by lymychp** [comment]
moved to [health](https://github.com/Nebo15/ehealth.api/issues/90)
