### ISSUE TITLE
[IL] Verify code

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/prm.api#74]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/phone-verification/verify-code)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Verify+code)

**Comment by lymychp** [comment]
moved to [ehealth](https://github.com/Nebo15/ehealth.api/issues/92)
