### ISSUE TITLE
[IL] Create legal entity

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/prm.api#83]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Create+Legal+Entity)

**Comment by mmiliaieva** [comment]
Transferred to ehealth.api
